Click_Check_Chat_Buy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    

]

# Static URL patterns
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

accounts/urls.py
app_name = 'accounts'
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.Click_Check_Chat_BuyLogin, name='Click_Check_Chat_BuyLogin'),
    path('register/', views.Click_Check_Chat_BuyRegister, name='Click_Check_Chat_BuyRegister'),
    path('forgotpassword/', views.forgotpassword, name='forgotpassword'),
    path('logout/', views.user_logout, name='user_logout'),
]

index/urls.py
app_name = 'index'
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('searchview/',views.searchview,name="search"),
    # path('index/', views.elcetronic, name='electronic'),
    path('buypage/<int:item_id>/', views.buypage, name='buypage'),
     path('category/<str:name>/', views.category_view, name='categoryview'),
    path('uploaditem/', views.uploaditem, name='uploaditem'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('chat/<int:id>/', views.chat_view, name='chat'),
    path('myprofile/', views.my_profile, name='my_profile'),
    path('delete/<int:id>/', views.deleteitem, name='delete_item'),
    path('wishlist/<int:id>/', views.wishlist_item, name='wishlist_item'),
    path('items/<int:item_id>/edit/', views.edit_item, name='edit_item'),
    path('new-message/',views.new_message,name="new_message"),
    path('wishlist/',views.wishlist_view,name="wishlist_view"),
    path('w_delete/<int:id>/', views.w_deleteitem, name='w_delete_item'),
    path('buy-now/',views.buynow,name='buy'),
    path('buynow/',views.buynow,name='buy'),

    
    # path('razorpayView/',views.razorpayView,name='razorpayView'),
    # path('paymenthandler/', views.paymenthandler, name='paymenthandler'),
    path('orderSuccessView/',views.successview,name='orderSuccessView'),
    path('my-order/',views.myorder,name='myorder'),
    path('paypal-payment/', views.paypal_payment, name='paypal_payment'),
    path('paypal-payment/success/', views.paypal_payment_success, name='paypal_payment_success'),
    path('paypal-payment/cancel/', views.paypal_payment_cancel, name='paypal_payment_cancel'),
 


]

templates/Click_Check_Chat_BuyLogin.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Login Page</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
	<link rel="stylesheet" href="{% static 'styles/styles.css' %}">
	
	<script>
	$(window).scroll(function() {
		  if ($(window).scrollTop() > 0) {
			$('.navbar-bottom').addClass('fixed');
		  } else {
			$('.navbar-bottom').removeClass('fixed');
		  }
		});
	</script>

</head>
	
<body style="background-color:#D3D3A3;">
	<!-- The Top Navbar -->
	<nav class="navbar navbar-expand-lg fixed-top d-flex justify-content-between" style="background: linear-gradient(45deg, #556B2F, #8FBC8F);">
		<div class="container-fluid">
			<a class="navbar-brand" href="{% url 'index:index' %}">
				<!-- <img src="{% static 'images/logo6.jpg' %}" alt="Click Check Chat Buy" id="qlogo"/> -->
				<img src="/static/images/logo-bg.png" alt="Click Check Chat Buy" id="qlogo" style="width: 275px; height: 30px;">
			</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav ms-auto">
					<li class="nav-item">
					  <a class="nav-link text-dark" href="{% url 'index:index' %}">Home</a>
					</li>
					<li class="nav-item">
					  <a class="nav-link text-dark" href="{% url 'accounts:Click_Check_Chat_BuyRegister' %}">Register</a>
					</li>
					<!--
					<li class="nav-item">
					  <a class="nav-link" href="#">Login</a>
					</li>
					-->
				</ul>
			</div>
		</div>
	</nav>
	

	{% if messages %}
	<div class="container mt-4">
		{% for message in messages %}
		<div class="alert alert-{{ message.tags }}" role="alert">
			{{ message }}
		</div>
		{% endfor %}
	</div>
	{% endif %}
	<!-- The main container -->
	<div class="container">
		
	  <div class="row justify-content-center">
		<div class="col-md-6">
		  <div class="login-form">
			<h2 class="text-center">Login</h2>
			<form action="{% url 'accounts:Click_Check_Chat_BuyLogin' %}" method="post">
				{% csrf_token %}
			  <div class="mb-3">
				<label for="username" class="form-label">Username</label>
				<input type="text" class="form-control" id="username" name="username" placeholder="Enter your username">
			  </div>
			  <div class="mb-3">
				<label for="password" class="form-label">Password</label>
				<input type="password" class="form-control" id="password" name="password" placeholder="Enter your password">
			  </div>
			  <div class="mb-3">
				<button type="submit" class="btn btn-primary">Login</button>
				<br><br>
				<a href="{% url 'accounts:forgotpassword' %}">Forgot password?</a>
			  </div>
			</form>
		  </div>
		</div>
	  </div>
	</div>

	<!-- Bottom Footer -->
	<!--

	-->
	
	<!-- The Bottom Navbar -->
	<nav class="navbar fixed-bottom navbar-light bg-light navbar-bottom mt-2">
		<div class="container-fluid">
			<p>&copy; 2024 Click Check Chat Buy. All rights reserved.</p>
		</div>
	</nav>

</body>
</html>

templates/Click_Check_Chat_BuyRegister.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>User Registration Page</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
	<link rel="stylesheet" href="{% static 'styles/styles.css' %}">
	
	<script>
	$(window).scroll(function() {
		  if ($(window).scrollTop() > 0) {
			$('.navbar-bottom').addClass('fixed');
		  } else {
			$('.navbar-bottom').removeClass('fixed');
		  }
		});
	</script>

</head>
	
<body style="background-color:#D3D3A3;">
	<nav class="navbar navbar-expand-lg fixed-top d-flex justify-content-between" style="background: linear-gradient(45deg, #556B2F, #8FBC8F);">
		<div class="container-fluid">
			<a class="navbar-brand" href="{% url 'index:index' %}">
				<!-- <img src="{% static 'images/logo6.jpg' %}" alt="Click Check Chat Buy" id="qlogo"/> -->
				<img src="/static/images/logo-bg.png" alt="Click Check Chat Buy" id="qlogo" style="width: 275px; height: 30px;">
			</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav ms-auto">
					
				
					<li class="nav-item">
						<a class="nav-link text-dark" href="{% url 'index:index' %}">Home</a>
					</li>
					<li class="nav-item">
					  <a class="nav-link text-dark" href="{% url 'accounts:Click_Check_Chat_BuyLogin' %}">Login</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>



	<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-6">
		<div class="login-form">
			{% if messages %}
  <div class="container mt-4">
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }}" role="alert">
          {{ message }}
      </div>
      {% endfor %}
  </div>
  {% endif %} 
			<h2 class="text-center">Register</h2>
			<form action="{% url 'accounts:Click_Check_Chat_BuyRegister' %}" method="post">
				{% csrf_token %}
			<div class="form-group">
				<label for="first_name" class="form-label">First Name</label>
				<input type="text" class="form-control" id="first_name" name="first_name" placeholder="Enter your First Name">
			</div>
			<div class="form-group">
				<label for="last_name" class="form-label">Last Name</label>
				<input type="text" class="form-control" id="last_name" name="last_name" placeholder="Enter your Last Name">
			</div>
			<div class="form-group">
				<label for="email" class="form-label">Email Address</label>
				<input type="text" class="form-control" id="email" name="email" placeholder="Enter your Email">
			</div>
			<div class="form-group">
				<label for="username" class="form-label">Set your Username</label>
				<input type="text" class="form-control" id="username" name="username" placeholder="Enter your username">
			</div>
			<div class="form-group">
				<label for="password" class="form-label">Password</label>
				<input type="password" class="form-control" id="password" name="password" placeholder="Enter your password">
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-primary">Register</button>
				<br><br>
			</div>
			</form>
		</div>
		</div>
	</div>
	</div>
	
	<nav class="navbar fixed-bottom navbar-light bg-light navbar-bottom mt-2">
		<div class="container-fluid">
			<p>&copy; 2024 Click Check Chat Buy. All rights reserved.</p>
		</div>
	</nav>

</body>
</html>

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Click Check Chat Buy - Meet and chat with the sellers</title>
        <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
            crossorigin="anonymous"
        />
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"
        ></script>
        <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css"
        />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <link rel="stylesheet" href="{% static 'styles/styles.css' %}" />

        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> <!-- jQuery library addon -->


        <script>
            $(document).ready(function () {
                $("#sidebar-toggle").click(function () {
                    $(".sidebar").toggleClass("active");
                });
            });

            $(document).ready(function () {
                $("#sidebar").on("show.bs.collapse", function () {
                    $(this).scrollTop(0);
                });
            });

            $(window).scroll(function () {
                if ($(window).scrollTop() > 0) {
                    $(".navbar-bottom").addClass("fixed");
                } else {
                    $(".navbar-bottom").removeClass("fixed");
                }
            });
        </script>
    </head>

    <body style="background-color: #D3D3A3;">
        <!-- Top navbar -->
        <nav class="navbar navbar-expand-lg fixed-top d-flex justify-content-between" style="background: linear-gradient(45deg, #556B2F, #8FBC8F);">
            <div class="container-fluid">

                <a class="navbar-brand" href="{% url 'index:index' %}">
                    <img src="{% static 'images/logo-bg.png' %}" alt="Click Check Chat Buy" id="qlogo" style="width: 275px; height: 30px;"/>
                </a>

                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNav"
                    aria-controls="navbarNav"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                    style="border-color: white;"
                >
                    <span class="navbar-toggler-icon" style="background-color: white;"></span>
                </button>
        
                <div class="navbar-collapse collapse" id="navbarNav">
                    <a class="sidebar-toggle" id="sidebar-toggle">
                        <i class="bi bi-list"></i>
                    </a>
                </div>

                      <!-- Add a new row for the search bar and button -->
        <div class="input-group">
            <div class="col-md-6">
                <form action="{% url 'index:search' %}" method="get">

                <div class="search-container" style="margin-left: 15px; margin-right: 15px;">
                    <input
                        type="text"
                        class="form-control"
                        placeholder="Search Items....."
                        id="searchInput"
                        name="search"
                    />
                </div>
              
            </div>
            <div class="col-md-6">
                <button type="submit" class="btn btn-primary ms-2">Search</button>
            </div>
        </form>
        </div>


            {% comment %} <!-- Add a container to display search results -->
            <div id="searchResults"></div>
            
            <script>
                $(document).ready(function () {
                    var placeholderText = "Search Items.....";
                    var currentCharacter = 0;
            
                    function typePlaceholder() {
                        var currentText = placeholderText.substring(0, currentCharacter + 1);
                        $("#searchInput").attr("placeholder", currentText);
                        currentCharacter++;
            
                        if (currentCharacter < placeholderText.length) {
                            setTimeout(typePlaceholder, 150);
                        }
                    }
            
                    // This will trigger the typing animation when the document is ready
                    typePlaceholder();
                });
            
                // Function to perform the search
                function performSearch() {
                    var searchQuery = $("#searchInput").val();
            
                    // AJAX request to Django API endpoint
                    $.ajax({
                        type: "GET",
                        url: "/api/search/", // Replace with your Django API endpoint URL
                        data: { query: searchQuery },
                        success: function (data) {
                            // Display the search results in the searchResults div
                            $("#searchResults").html(data);
                        },
                        error: function (error) {
                            console.error("Error during search:", error);
                        }
                    });
                }
            </script>
                <script>
                    $(document).ready(function () {
                        var placeholderText = "Search Items.....";
                        var currentCharacter = 0;
                
                        function typePlaceholder() {
                            var currentText = placeholderText.substring(0, currentCharacter + 1);
                            $("#searchInput").attr("placeholder", currentText);
                            currentCharacter++;
                
                            if (currentCharacter < placeholderText.length) {
                                setTimeout(typePlaceholder, 150); // This will adjust the speed (in milliseconds)
                            }
                        }
                
                        // This will trigger the typing animation when the document is ready
                        typePlaceholder();
                    });
                </script>
                
            </div> {% endcomment %}
        </nav>
        <br /><br />

        <!-- Side Panel Code -->

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-3">
                    <div class="sidebar">
                        <br/><br/><br/>
                        <h2>Categories</h2>
                        <ul class="list-group">
                            {% for i in category %}
                            <li class="list-group-item">
                             <a href="{% url "index:categoryview" i.name %}">{{i.name}}</a>
                            </li>
                            {% endfor %}
                        </ul>

                        <hr />

                        <h2>Search</h2>
                        <form action="{% url 'index:search' %}" method="get">
                                <input
                                    type="text"
                                    class="form-control"
                                    placeholder="Search Items....."
                                    id="searchInput"
                                    name="search"
                                />
                      
                    </form>
                       <hr />
                        
                        <h2>My Account</h2>
                        {% if user.is_authenticated %}
                        <ul class="list-group">
                            <li class="list-group-item">
                                <a href="{% url 'index:my_profile' %}">My Profile</a>
                            </li>
                            <li class="list-group-item">
                                <a href="{% url 'index:uploaditem' %}">Upload New Item</a>
                            </li>
                            <!-- Commented out wishlist item -->
                             <li class="list-group-item">
                                <a href="{% url "index:wishlist_view" %}">My Wishlist</a>
                            </li>
                            <li class="list-group-item">
                                <a href="{% url "index:new_message" %}">Chat</a>
                            </li>
                            <li class="list-group-item">
                                <a href="{% url "index:myorder" %}">My Orders</a>
                            </li>
                            
                            <li class="list-group-item">
                                <a href="{% url 'accounts:user_logout' %}">Logout</a>
                            </li>
                        </ul>
                    {% else %}
                        <ul class="list-group">
                            <li class="list-group-item">
                                <a href="{% url 'accounts:Click_Check_Chat_BuyRegister' %}">Register</a>
                            </li>
                            <li class="list-group-item">
                                <a href="{% url 'accounts:Click_Check_Chat_BuyLogin' %}">Login</a>
                            </li>
                        </ul>
                    {% endif %}
                    
                       <hr />

                        <ul class="list-group">
                            <li class="list-group-item">
                                <a href="{% url 'index:aboutus' %}">About Us</a>
                            </li>
                        </ul>
                    </div>
                </div>
                {% if messages %}
  <div class="container mt-4">
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }}" role="alert">
          {{ message }}
      </div>
      {% endfor %}
  </div>
  {% endif %} 

                {% block content %}
                
                {% endblock  %}



        <!-- Bottom navbar -->
        <nav class="navbar fixed-bottom navbar-light navbar-bottom" style="background-color: #D3D3A3; height: 40px;">
            <div class="container-fluid">
                <p>&copy; 2024 Click Check Chat Buy.</p>
            </div>
        </nav>
    </body>
</html>

templates/buypage.html
{% extends "base.html" %}
{% load static %}
{% block content %}			
			<div class="col-md-1"></div>
			<div class="col-md-12">
				<!-- Item details starts here -->
				<div class="card mb-3 p-2" style="margin: 20px auto auto auto; width: 50%; height: auto;">
					<div class="card-body">
						<h3 class="card-title">{{ item.name }}</h3>
						<br>
						
						<!-- Display item image with responsive class -->
						{% if item.image_encoded %}
						<img src="data:image/png;base64, {{ item.image_encoded }}" class="card-img-top img-fluid border border-2" alt="{{ item.name }}" height="550px">
						{% else %}
						<img src="{{ item.photos.url }}" class="card-img-top img-fluid border border-2" alt="{{ item.name }}" height="550px">
						{% endif %}
						<p class="card-text mt-3">{{ item.description }}</p>
						<p class="card-text mt-3"><b>Item Category:&nbsp</b>{{ item.category }}</p>
						<p class="card-text mt-3"><b>Item Condition:&nbsp</b>{{ item.condition }}</p>

						<p class="card-text mt-3"><b>Price:&nbsp</b>{{ item.price }}</p>
						
						<!-- Chat with seller form -->
						{% if request.user != item.seller_id %}
						<div style="display: inline-block;">
							<a class="btn btn-primary" href="{% url 'index:chat' item.seller_id.pk %}">Chat with seller</a>
							<form action="{% url 'index:wishlist_item' item.pk %}" method="post" style="display: inline;">
								{% csrf_token %}
								<input type="hidden" name="item_price" value="{{ item.price }}">
								
								<button type="submit" class="btn btn-primary">Add to wishlist</button>
							</form>
							<form action="{% url 'index:buy' %}" method="post" style="display: inline;">
								{% csrf_token %}
								<input type="hidden" name="item_id" value="{{ item.pk }}">
								<button type="submit" class="btn btn-primary">Buy now</button>
							</form>
						</div>
						{% endif %}
					</div>
				</div>
			</div>
			

			<!-- Items part ends here-->
		</div>
	</div>

	{% endblock %}

templates/homepage.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    {% if items %}
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for item in items %}
            <div class="col">
                <div class="card h-100">
                    <a href="{% url 'index:buypage' item_id=item.item_id %}">
                        <img
                            src="data:image/png;base64, {{ item.image_encoded }}"
                            alt="{{ item.name }}"
                            class="card-img-top"
                            width="200"
                            height="200"
                        />
                    </a>
                    
                    <div class="card-body">
                        <h5 class="card-title">{{ item.name }}</h5>
                        <p class="card-text">{{ item.description }}</p>
                        <p class="card-text">{{ item.condition }}</p>
                        <p class="card-text">
                            <strong>Price: {{ item.price }}</strong>
                        </p>
                        {% comment %} <button type="button" class="btn btn-primary">
                            Buy Now
                        </button> {% endcomment %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% else %}
<div class="alert alert-info" role="alert">
No products available.
</div>
{% endif %}
</div>

<div class="col-md-9">
    
</div>
</div>
</div>

{% endblock  %}

templates/myprofile.html
{% extends "base.html" %}
{% block content %}


<div class="row p-5">
    
    <div class="col-md-4">
            <h1>My Profile</h1>
            <h2 class="mt-3">{{ user.get_full_name }}</h2>
            <p><b>First Name:</b> {{ user.first_name }}</p>
            <p><b>Last Name:</b> {{ user.last_name }}</p>
            <p><b>Email Address:</b> {{ user.email }}</p>
        </div>

        <div class="col-md-8">
            <div class="container">
                <h2>Uploaded Items</h2>
                <br>
                <div class="row  g-4">
                    {% for item in uploaded_items %}
                        <div class="col-md-4">
                            <div class="card h-100">
                                {% if item.image_encoded %}
                                <img src="data:image/png;base64, {{ item.image_encoded }}" class="card-img-top img-fluid border border-2" alt="{{ item.name }}" height="550px">
                                {% else %}
                                <img src="{{ item.photos.url }}" class="card-img-top img-fluid border border-2" alt="{{ item.name }}" height="550px">
                                {% endif %}
                                <div class="card-body">
                                    <h5 class="card-title">{{ item.name }}</h5>
                                    <p class="card-text">{{ item.description }}</p>
                                    <p class="card-text">{{ item.condition }}</p>
                                    <p class="card-text"><strong>Price: ${{ item.price }}</strong></p>
                                    <a href="{% url "index:edit_item" item.pk %}" class="btn btn-primary">Edit Item</a>
                                    <a href="{% url "index:delete_item" item.pk %}" class="btn btn-danger">Delete</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
    </div>
</div>

{% endblock  %}

templates/order_sucess.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


    <section class="signup">
        <div class="container">
            <div class="signup-content">
                <div class="signup-form">
                    <h2 class="form-title">Order Sucessfully Placed</h2>
                    <a href="{% url "index:index" %}" class="btn btn-primary">Go to Home Page</a>
                </div>
            </div>
        </div>
    </section>


{% endblock %}

templates/razorpayDemo.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Razorpay Payment Page</title>
  </head>
  <!-- Razorpay's Javascript code. -->
  <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
  <script>
    var options = {
       
      // Enter the Key ID generated from the Dashboard
      key: "{{ razorpay_merchant_key }}",
       
      // Amount is in currency subunits.
      // Default currency is INR. Hence,
      // 50000 refers to 50000 paise
      amount: "{{ razorpay_amount }}",
      currency: "{{ currency }}",
      // Your/store name.
      name: "Click Check Chat Buy",
      prefill : {
        name : 'Rudra',
        email : 'rudra15041998@gmail.com',
        contact : '9696451100',
      },
      theme: {
        color: "#3399cc",
      },
      // Pass the `id` obtained in the response of Step 1
      order_id: "{{ razorpay_order_id }}",
      callback_url: "{{ callback_url }}",
    };
     
    // initialise razorpay with the options.
    var rzp1 = new Razorpay(options);
    rzp1.open();
  </script>
</html>

templates/wishlist.html
{% extends "base.html" %}
{% load static %}
{% block content %}	    

<div class="container-fluid">
        <div class="row p-4">
            
            <div class="col-md-12">
                <!-- Cart Items -->
                    <h1>Shopping wish list</h1>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Product</th>
                                <th scope="col">Price</th>
                                <th scope="col">Quantity</th>
                                <th scope="col">Total</th>
                                <th scope="col">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- Loop through cart items -->
                            {% for item in wish %}
                            <tr>
                                <td>{{ item.productname }}</td>
                                <td>{{ item.productprice }}</td>
                                <td>
                                    {{ item.quantity }}
                                </td>
                                <td>{{ item.totalproductprice }}</td>
                                <td>
                                    <button class="btn btn-danger remove-btn" onclick="location.href='{% url "index:w_delete_item" item.cartId %}'">Remove</button>
                                </td>
                                <td>
                                    <button class="btn btn-primary " onclick="location.href='{% url 'index:buypage' item_id=item.productId %}'">View product</button>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div>
                        <div class="row align-items-center">
                            <div class="col-md-6">
                                <a href="{% url 'index:index' %}" class="btn btn-secondary">Continue Shopping</a>
                            </div>
                            
                        </div>
                    </div>
            </div>
        </div>
    </div>
	{% endblock %}